#!/usr/bin/env python3
"""
Transcript Formatter (Anthropic Claude API)
- Uses Claude API to format .transcript.md files
- Adds a 2-4 sentence summary at the top
- Improves markdown structure (headers, paragraphs, page breaks)
- Preserves all original transcribed words exactly
- Marks processed files with formatting: cleaned in frontmatter

Usage:
    python format_transcripts.py                                    # all transcripts
    python format_transcripts.py --folder Journals                  # one folder
    python format_transcripts.py --file path/to/file.transcript.md  # single file
    python format_transcripts.py --force                            # re-format cleaned files
    python format_transcripts.py --dry-run                          # list files, no API calls
    python format_transcripts.py --model claude-sonnet-4-20250514   # override model
"""

import os
import re
import sys
import json
import time
import argparse
from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, str(Path(__file__).parent))
from config import load_config, load_env

TODAY = datetime.now().strftime("%Y-%m-%d")
DEFAULT_MODEL = "claude-haiku-4-5-20251001"

PDF_FORMAT_PROMPT = """You are formatting a transcript of a scanned document for readability. The transcript was generated by OCR/AI vision and must remain word-for-word faithful to the original.

Your job:
1. Generate a 2-4 sentence summary of the document (who, what, when, notable content). Write it as a markdown blockquote (lines starting with >).
2. Format the body for pleasant reading using markdown:
   - Replace "## Page N" markers with "---" horizontal rules followed by a small italic page reference like *Page N*
   - Promote any headings, labels, or titles found in the content to markdown headers (##, ###)
   - Add section headers where the document has natural divisions (dated entries, topic shifts)
   - Use bold, italic, blockquotes, or lists where they improve readability (e.g., recipe ingredients as a bulleted list)
   - Fix paragraph breaks and whitespace for natural reading flow
   - Remove obvious scan artifacts (barcode numbers, copyright boilerplate, printer registration marks, ISBN codes)
   - Do NOT remove image descriptions like ![description]

CRITICAL RULES:
- Do NOT change, correct, rephrase, or omit any human-written words
- Preserve original spelling, grammar, and punctuation exactly as transcribed
- Only add structural markdown — never alter content
- If unsure whether something is human content or artifact, keep it

Document metadata:
- Type: {doc_type}
- Date: {date}
- Source: {source_file}

Transcript body:
{body}

Please return your response as a JSON object with these fields:
- "summary": a 2-4 sentence summary formatted as a markdown blockquote (lines starting with >)
- "formatted_body": the complete formatted markdown body

Return only the JSON object, no other text."""

AUDIO_FORMAT_PROMPT = """You are formatting a transcript of an audio recording for readability. The transcript was generated by speech-to-text AI with speaker diarization and must remain word-for-word faithful to the original.

Your job:
1. Generate a 2-4 sentence summary (who is speaking, what they discuss, notable moments). Write it as a markdown blockquote (lines starting with >).
2. Create a natural, descriptive title for the recording (replace the generic slug-based title).
3. Format the body for pleasant reading:
   - Break long speaker blocks into paragraphs where topics naturally shift
   - Add approximate timestamps to new paragraphs. Interpolate between the speaker's start and end times based on word position. Format as **Speaker X** (M:SS - M:SS):
   - Add topic headers (### Header) at major topic shifts to help navigate long recordings
   - Keep the **Speaker X** (timestamp) format for speaker labels
   - Use markdown features (bold, italic, blockquotes) where they improve readability
   - For music/singing sections, you may use italic to distinguish lyrics from speech

CRITICAL RULES:
- Do NOT change, correct, rephrase, or omit any spoken words
- Preserve the exact transcription including verbal tics, repetitions, partial sentences
- Only add structural markdown — never alter content
- Approximate timestamps should be reasonable interpolations within the speaker's time range
- If a recording is a song performance, keep it as-is with minimal formatting (no topic headers needed)

Audio metadata:
- Date: {date}
- Duration: {duration}
- Speakers: {speaker_count}
- Source: {source_file}

Transcript body:
{body}

Please return your response as a JSON object with these fields:
- "summary": a 2-4 sentence summary formatted as a markdown blockquote (lines starting with >)
- "title": a natural, descriptive title for the recording
- "formatted_body": the complete formatted markdown body

Return only the JSON object, no other text."""


def parse_frontmatter(content):
    """Parse YAML frontmatter and body from a transcript file.
    Returns (frontmatter_text, frontmatter_dict, body)."""
    if not content.startswith("---"):
        return "", {}, content

    parts = content.split("---", 2)
    if len(parts) < 3:
        return "", {}, content

    fm_text = parts[1].strip()
    body = parts[2].strip()

    fm_dict = {}
    for line in fm_text.split("\n"):
        line = line.strip()
        if ":" in line and not line.startswith("#") and not line.startswith("-"):
            key, _, val = line.partition(":")
            fm_dict[key.strip()] = val.strip()

    return fm_text, fm_dict, body


def rebuild_file(fm_text, summary, formatted_body, title=None, original_title_line=None):
    """Rebuild the transcript file with formatting: cleaned added."""
    if "formatting:" not in fm_text:
        fm_text += "\nformatting: cleaned"
    else:
        fm_text = re.sub(r"formatting:.*", "formatting: cleaned", fm_text)

    parts = [f"---\n{fm_text}\n---\n"]

    if summary:
        parts.append(f"\n{summary}\n")

    if title:
        parts.append(f"\n# {title}\n")
    elif original_title_line:
        parts.append(f"\n{original_title_line}\n")

    if formatted_body:
        parts.append(f"\n{formatted_body}\n")

    return "\n".join(parts)


def detect_type(fm_dict):
    """Detect transcript type from frontmatter fields."""
    method = fm_dict.get("transcription_method", "")
    tool = fm_dict.get("transcription_tool", "")

    if "AssemblyAI" in tool or "Whisper" in tool:
        return "audio"
    if "ai-vision" in method or "native" in method or "ocr" in method:
        return "pdf"
    return "pdf"


CHUNK_WORD_LIMIT = 8000  # split large transcripts into chunks of ~8000 words


def split_into_chunks(body):
    """Split a transcript body into chunks by page markers, staying under word limit."""
    # Split by page markers
    page_pattern = re.compile(r"(?=\n## Page \d+)")
    pages = page_pattern.split(body)
    pages = [p for p in pages if p.strip()]

    if not pages:
        return [body]

    chunks = []
    current_chunk = []
    current_words = 0

    for page in pages:
        page_words = len(page.split())
        if current_words + page_words > CHUNK_WORD_LIMIT and current_chunk:
            chunks.append("\n".join(current_chunk))
            current_chunk = [page]
            current_words = page_words
        else:
            current_chunk.append(page)
            current_words += page_words

    if current_chunk:
        chunks.append("\n".join(current_chunk))

    return chunks


SUMMARY_PROMPT = """Read this excerpt from the beginning of a document and write a 2-4 sentence summary of the overall document (who, what, when, notable content). Write it as a markdown blockquote (lines starting with >).

Document metadata:
- Type: {doc_type}
- Date: {date}
- Source: {source_file}

Excerpt (first pages):
{excerpt}

Return ONLY the blockquote summary, nothing else."""

CHUNK_FORMAT_PROMPT = """You are formatting a section of a transcript for readability. The transcript was generated by OCR/AI vision and must remain word-for-word faithful to the original.

Format this section using markdown:
- Replace "## Page N" markers with "---" horizontal rules followed by a small italic page reference like *Page N*
- Promote any headings, labels, or titles found in the content to markdown headers (##, ###)
- Add section headers where the document has natural divisions (dated entries, topic shifts)
- Use bold, italic, blockquotes, or lists where they improve readability
- Fix paragraph breaks and whitespace for natural reading flow
- Remove obvious scan artifacts (barcode numbers, copyright boilerplate, printer registration marks)
- Do NOT remove image descriptions like ![description]

CRITICAL RULES:
- Do NOT change, correct, rephrase, or omit any human-written words
- Preserve original spelling, grammar, and punctuation exactly
- Only add structural markdown — never alter content

Transcript section:
{body}

Return ONLY the formatted markdown, no JSON wrapper, no explanation."""


RETRYABLE_STATUSES = {"overloaded_error", "rate_limit_error", "api_error"}
MAX_RETRIES = 3


def call_claude(client, model_name, prompt, max_tokens=16000):
    """Make a Claude API call with streaming and retries."""
    for attempt in range(MAX_RETRIES + 1):
        try:
            # Use streaming to avoid the 10-minute timeout for large responses
            text_parts = []
            with client.messages.stream(
                model=model_name,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            ) as stream:
                for text in stream.text_stream:
                    text_parts.append(text)
            return "".join(text_parts)
        except Exception as e:
            err_type = getattr(e, "status_code", None)
            err_str = str(e)
            is_retryable = (
                any(s in err_str for s in RETRYABLE_STATUSES)
                or (err_type and err_type in {429, 500, 502, 503, 504, 529})
            )
            if is_retryable and attempt < MAX_RETRIES:
                wait = 2 ** attempt * 10  # longer backoff for rate limits
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} after {wait}s ({err_str[:60]}...)")
                time.sleep(wait)
                continue
            raise


def format_large_transcript(client, model_name, body, fm_dict):
    """Format a large transcript by splitting into chunks."""
    chunks = split_into_chunks(body)
    print(f"    Splitting into {len(chunks)} chunks")

    # Generate summary from first chunk
    excerpt = chunks[0][:5000]
    summary_prompt = SUMMARY_PROMPT.format(
        doc_type=fm_dict.get("document_type", "document"),
        date=fm_dict.get("estimated_date", "unknown"),
        source_file=fm_dict.get("source_file", "unknown"),
        excerpt=excerpt,
    )
    summary = call_claude(client, model_name, summary_prompt, max_tokens=500)

    # Format each chunk
    formatted_chunks = []
    for i, chunk in enumerate(chunks):
        print(f"    Formatting chunk {i + 1}/{len(chunks)} ({len(chunk.split())} words)")
        chunk_prompt = CHUNK_FORMAT_PROMPT.format(body=chunk)
        formatted = call_claude(client, model_name, chunk_prompt, max_tokens=min(len(chunk.split()) * 3, 32000))
        formatted_chunks.append(formatted)

    return {
        "summary": summary.strip(),
        "formatted_body": "\n\n".join(formatted_chunks),
    }


def format_via_claude(client, model_name, body, fm_dict, transcript_type):
    """Send transcript to Claude API for formatting, with retries."""
    if transcript_type == "audio":
        prompt = AUDIO_FORMAT_PROMPT.format(
            date=fm_dict.get("estimated_date", "unknown"),
            duration=fm_dict.get("duration", "unknown"),
            speaker_count=fm_dict.get("speaker_count", "unknown"),
            source_file=fm_dict.get("source_file", "unknown"),
            body=body,
        )
    else:
        prompt = PDF_FORMAT_PROMPT.format(
            doc_type=fm_dict.get("document_type", "document"),
            date=fm_dict.get("estimated_date", "unknown"),
            source_file=fm_dict.get("source_file", "unknown"),
            body=body,
        )

    for attempt in range(MAX_RETRIES + 1):
        try:
            # Estimate max tokens needed (~2x input for formatted output + summary)
            input_words = len(body.split())
            max_tokens = min(max(input_words * 3, 1000), 128000)

            text_parts = []
            with client.messages.stream(
                model=model_name,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            ) as stream:
                for text in stream.text_stream:
                    text_parts.append(text)
            response_text = "".join(text_parts)

            result = parse_response_json(response_text)
            if result is not None:
                return result

            if attempt < MAX_RETRIES:
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} (malformed JSON)")
                time.sleep(2)
                continue
            print(f"    Unparseable response: {response_text[:200]}...")
            return None

        except Exception as e:
            err_type = getattr(e, "status_code", None)
            err_str = str(e)
            is_retryable = (
                any(s in err_str for s in RETRYABLE_STATUSES)
                or (err_type and err_type in {429, 500, 502, 503, 504, 529})
            )
            if is_retryable and attempt < MAX_RETRIES:
                wait = 2 ** attempt * 5  # 5s, 10s, 20s
                print(f"    Retry {attempt + 1}/{MAX_RETRIES} after {wait}s ({err_str[:60]}...)")
                time.sleep(wait)
                continue
            raise


def parse_response_json(text):
    """Parse the JSON response from Claude."""
    cleaned = text.strip()
    cleaned = re.sub(r"^```json\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    cleaned = cleaned.strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r'\{.*\}', cleaned, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
        return None


def collect_transcripts(dest_root, target_folder=None, target_file=None, force=False):
    """Collect transcript files to process."""
    if target_file:
        p = Path(target_file)
        if not p.is_absolute():
            p = dest_root / p
        if not p.exists():
            print(f"ERROR: File not found: {p}")
            return []
        return [p]

    if target_folder:
        search_root = dest_root / target_folder
    else:
        search_root = dest_root

    all_transcripts = sorted(search_root.rglob("*.transcript.md"))

    result = []
    for t in all_transcripts:
        content = t.read_text(encoding="utf-8", errors="replace")
        if "transcription_confidence: pending" in content:
            continue
        if not force and "formatting: cleaned" in content:
            continue
        result.append(t)

    return result


def main():
    parser = argparse.ArgumentParser(description="Format transcripts with Claude API — summaries and markdown cleanup")
    parser.add_argument("--config", default=None, help="Path to config.json")
    parser.add_argument("--folder", default=None, help="Only format transcripts in this subfolder")
    parser.add_argument("--file", default=None, help="Format a single transcript file")
    parser.add_argument("--model", default=DEFAULT_MODEL, help=f"Claude model (default: {DEFAULT_MODEL})")
    parser.add_argument("--force", action="store_true", help="Re-format already-cleaned files")
    parser.add_argument("--dry-run", action="store_true", help="List files without formatting")
    args = parser.parse_args()

    if not args.dry_run:
        if not load_env():
            sys.exit(1)
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            print("ERROR: ANTHROPIC_API_KEY not set in .env file.")
            sys.exit(1)

    config = load_config(args.config)
    dest_root = config["dest_root"]

    transcripts = collect_transcripts(dest_root, args.folder, args.file, args.force)

    if not transcripts:
        print("No transcripts to format.")
        return

    print(f"Found {len(transcripts)} transcripts to format")
    print(f"Model: {args.model}")

    if args.dry_run:
        print("\n--- DRY RUN ---")
        by_folder = {}
        for t in transcripts:
            try:
                rel = t.relative_to(dest_root)
                folder = str(rel).split("\\")[0].split("/")[0]
            except ValueError:
                folder = "other"
            by_folder.setdefault(folder, []).append(t)

        for folder, files in sorted(by_folder.items()):
            print(f"\n  {folder}: {len(files)} files")
            for f in files[:3]:
                rel = f.relative_to(dest_root) if f.is_relative_to(dest_root) else f
                content = f.read_text(encoding="utf-8", errors="replace")
                _, fm, _ = parse_frontmatter(content)
                ttype = detect_type(fm)
                print(f"    {rel} [{ttype}]")
            if len(files) > 3:
                print(f"    ... and {len(files) - 3} more")
        return

    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    results = {"ok": 0, "error": 0, "skipped": 0}

    # Separate large files (chunked, serial) from small files (parallel)
    small_transcripts = []
    large_transcripts = []
    for t in transcripts:
        content = t.read_text(encoding="utf-8", errors="replace")
        _, _, body = parse_frontmatter(content)
        if len(body.split()) > CHUNK_WORD_LIMIT:
            large_transcripts.append(t)
        else:
            small_transcripts.append(t)

    if large_transcripts:
        print(f"  {len(large_transcripts)} large files (chunked, serial)")
    if small_transcripts:
        print(f"  {len(small_transcripts)} small files (parallel)")

    # Process large files first, serially (to avoid rate limits from many chunks)
    for i, t in enumerate(large_transcripts, 1):
        rel = t.relative_to(dest_root) if t.is_relative_to(dest_root) else t
        content = t.read_text(encoding="utf-8", errors="replace")
        fm_text, fm_dict, body = parse_frontmatter(content)
        transcript_type = detect_type(fm_dict)
        print(f"[large {i}/{len(large_transcripts)}] {rel} ({len(body.split()):,} words)")

        try:
            data = format_large_transcript(client, args.model, body, fm_dict)
            if not data or not data.get("formatted_body"):
                print(f"  ERROR: Failed to format")
                results["error"] += 1
                continue

            original_title_line = None
            if transcript_type == "pdf":
                title_match = re.match(r"^(# .+)$", body, re.MULTILINE)
                if title_match:
                    original_title_line = title_match.group(1)

            new_content = rebuild_file(fm_text, data["summary"], data["formatted_body"], data.get("title"), original_title_line)
            t.write_text(new_content, encoding="utf-8")
            print(f"  Done: {len(data['formatted_body'].split()):,} words")
            results["ok"] += 1
        except Exception as e:
            print(f"  ERROR: {str(e)[:100]}")
            results["error"] += 1

    # Process small files in parallel
    max_workers = 10

    def format_one(t):
        """Format a single transcript file. Returns (path, status, detail)."""
        content = t.read_text(encoding="utf-8", errors="replace")
        fm_text, fm_dict, body = parse_frontmatter(content)
        transcript_type = detect_type(fm_dict)

        if not body.strip():
            return t, "skipped", "empty body"

        try:
            word_count = len(body.split())
            if word_count > CHUNK_WORD_LIMIT:
                # Large file — use chunked formatting
                data = format_large_transcript(client, args.model, body, fm_dict)
            else:
                data = format_via_claude(client, args.model, body, fm_dict, transcript_type)

            if not data:
                return t, "error", "Failed to parse response"

            summary = data.get("summary", "")
            formatted_body = data.get("formatted_body", "")
            title = data.get("title")

            if not formatted_body:
                return t, "error", "Empty formatted body returned"

            original_title_line = None
            if transcript_type == "pdf":
                title_match = re.match(r"^(# .+)$", body, re.MULTILINE)
                if title_match:
                    original_title_line = title_match.group(1)

            new_content = rebuild_file(fm_text, summary, formatted_body, title, original_title_line)
            t.write_text(new_content, encoding="utf-8")

            word_count = len(formatted_body.split())
            return t, "ok", f"{word_count} words, summary added"

        except Exception as e:
            return t, "error", str(e)[:100]

    print(f"Processing with {max_workers} parallel workers...")

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(format_one, t): t for t in transcripts}
        done_count = 0
        for future in as_completed(futures):
            done_count += 1
            t, status, detail = future.result()
            rel = t.relative_to(dest_root) if t.is_relative_to(dest_root) else t
            results[status] = results.get(status, 0) + 1

            if status == "ok":
                print(f"  [{done_count}/{len(transcripts)}] {rel} — {detail}")
            elif status == "skipped":
                print(f"  [{done_count}/{len(transcripts)}] {rel} — SKIP: {detail}")
            else:
                print(f"  [{done_count}/{len(transcripts)}] {rel} — ERROR: {detail}")

    print(f"\n{'=' * 60}")
    print(f"Complete: {results['ok']} formatted, {results['error']} errors, {results['skipped']} skipped")


if __name__ == "__main__":
    main()
