#!/usr/bin/env python3
"""
Archive Summary Report Generator (Generalized)
Produces _archive-summary.md with collection statistics.

Usage:
    python generate_report.py                    # uses config.json
    python generate_report.py --config path.json
"""

import os
import re
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime
from collections import defaultdict

sys.path.insert(0, str(Path(__file__).parent))
from config import load_config

TODAY = datetime.now().strftime("%Y-%m-%d")

def format_size(b):
    for unit in ['B', 'KB', 'MB', 'GB']:
        if b < 1024:
            return f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} TB"

def count_files(root):
    counts = defaultdict(int)
    total_size = 0
    for dp, _, fns in os.walk(root):
        for f in fns:
            fp = Path(dp) / f
            ext = fp.suffix.lower()
            if ext in ('.md', '.json'):
                continue
            counts[ext] += 1
            try:
                total_size += fp.stat().st_size
            except OSError:
                pass
    return counts, total_size

def get_date_range(root):
    earliest, latest = "9999", "0000"
    for fp in root.rglob("*"):
        if fp.is_file() and fp.suffix.lower() not in ('.md', '.json'):
            m = re.search(r'(\d{4})-\d{2}-\d{2}', fp.name)
            if m:
                date = m.group(0)
                if "1800" < date < earliest:
                    earliest = date
                if date > latest and date < "2030":
                    latest = date
    return earliest, latest

def get_transcript_stats(root):
    stats = {"high": 0, "medium": 0, "low": 0, "pending": 0, "total": 0}
    for md in root.rglob("*.transcript.md"):
        stats["total"] += 1
        try:
            for line in md.read_text(encoding='utf-8', errors='replace').split('\n')[:15]:
                if line.startswith('transcription_confidence:'):
                    conf = line.split(':', 1)[1].strip()
                    if conf in stats:
                        stats[conf] += 1
                    break
        except Exception:
            pass
    return stats

def main():
    parser = argparse.ArgumentParser(description="Archive Report Generator")
    parser.add_argument("--config", default=None)
    args = parser.parse_args()

    config = load_config(args.config)
    dest_root = config["dest_root"]

    print("Generating report...")

    # Folder stats
    folder_stats = {}
    total_files = total_size = 0
    for item in sorted(dest_root.iterdir()):
        if item.is_dir() and item.name not in ("_scripts", "Toolkit"):
            counts, size = count_files(item)
            fc = sum(counts.values())
            if fc > 0:
                folder_stats[item.name] = {"count": fc, "size": size}
                total_files += fc
                total_size += size

    earliest, latest = get_date_range(dest_root)
    trans = get_transcript_stats(dest_root)
    audio_count = len(list(dest_root.rglob("AudioRecordings/**/*.transcript.md")))
    audio_total = len([f for f in dest_root.rglob("AudioRecordings/**/*")
                       if f.is_file() and f.suffix.lower() in ('.mp3','.wav','.m4a','.flac')])
    nr_count = len([f for f in (dest_root / "NeedsReview").rglob("*")
                    if f.is_file() and f.suffix.lower() not in ('.md','.json')]) if (dest_root / "NeedsReview").exists() else 0

    report = f"""# Archive Summary Report

Generated: {TODAY}

## Overview

| Metric | Value |
|--------|-------|
| Total files | {total_files:,} |
| Total size | {format_size(total_size)} |
| Date range | {earliest} to {latest} |
| Transcripts | {trans['total']} |
| Audio transcripts | {audio_count} / {audio_total} |
| Files needing review | {nr_count} |

## Files by Category

| Category | Files | Size |
|----------|-------|------|
"""
    for folder, s in sorted(folder_stats.items(), key=lambda x: -x[1]["count"]):
        report += f"| {folder} | {s['count']:,} | {format_size(s['size'])} |\n"
    report += f"| **TOTAL** | **{total_files:,}** | **{format_size(total_size)}** |\n"

    report += f"""
## Transcription Confidence

| Level | Count |
|-------|-------|
| High | {trans['high']} |
| Medium | {trans['medium']} |
| Low | {trans['low']} |
| Pending | {trans['pending']} |
| **Total** | **{trans['total']}** |

## Recommended Next Steps

1. Review files in `NeedsReview/` — {nr_count} files could not be classified automatically
2. Review low-confidence transcriptions ({trans['low']} files) for manual correction
3. Photos with generic filenames should be reviewed and given descriptive names
4. Audio transcriptions should be spot-checked for accuracy

---
*Generated by Archive Organizer Toolkit on {TODAY}*
"""

    report_path = dest_root / "_archive-summary.md"
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report)
    print(f"Report written to {report_path}")

if __name__ == "__main__":
    main()
